[package]
name = "mini-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4"
regex = "1.10"
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wait-timeout = "0.2"
